// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU_AG7vRo3QjwMAk-FtuvgwT496PlD_9s',
    appId: '1:12093340426:web:2cee37bf0c3c8aa7dd98f3',
    messagingSenderId: '12093340426',
    projectId: 'authgallery-85d51',
    authDomain: 'authgallery-85d51.firebaseapp.com',
    storageBucket: 'authgallery-85d51.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaYIRGlk8PCIeDQN2oqVdgwGFpSAiBo8c',
    appId: '1:12093340426:android:0a59c1d5f9e234ebdd98f3',
    messagingSenderId: '12093340426',
    projectId: 'authgallery-85d51',
    storageBucket: 'authgallery-85d51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtaTNJ3DBuigtD2puA6njHw-vTZzs-Ko8',
    appId: '1:12093340426:ios:44d7a65cc16bfc3add98f3',
    messagingSenderId: '12093340426',
    projectId: 'authgallery-85d51',
    storageBucket: 'authgallery-85d51.appspot.com',
    iosBundleId: 'com.example.snapc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtaTNJ3DBuigtD2puA6njHw-vTZzs-Ko8',
    appId: '1:12093340426:ios:fd6f82a48bf749bddd98f3',
    messagingSenderId: '12093340426',
    projectId: 'authgallery-85d51',
    storageBucket: 'authgallery-85d51.appspot.com',
    iosBundleId: 'com.example.snapc.RunnerTests',
  );
}
